<?php

declare(strict_types=1);

/*
 * TwilioMessagingSMSLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioMessagingSMSLib\Models\Builders;

use Core\Utils\CoreHelper;
use TwilioMessagingSMSLib\Models\AvailablePhoneNumber;

/**
 * Builder for model AvailablePhoneNumber
 *
 * @see AvailablePhoneNumber
 */
class AvailablePhoneNumberBuilder
{
    /**
     * @var AvailablePhoneNumber
     */
    private $instance;

    private function __construct(AvailablePhoneNumber $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new available phone number Builder object.
     */
    public static function init(
        string $addressRequirements,
        bool $beta,
        array $capabilities,
        string $friendlyName,
        string $isoCountry,
        string $lata,
        float $latitude,
        string $locality,
        float $longitude,
        string $phoneNumber,
        string $postalCode,
        string $rateCenter,
        string $region
    ): self {
        return new self(new AvailablePhoneNumber(
            $addressRequirements,
            $beta,
            $capabilities,
            $friendlyName,
            $isoCountry,
            $lata,
            $latitude,
            $locality,
            $longitude,
            $phoneNumber,
            $postalCode,
            $rateCenter,
            $region
        ));
    }

    /**
     * Initializes a new available phone number object.
     */
    public function build(): AvailablePhoneNumber
    {
        return CoreHelper::clone($this->instance);
    }
}
