<?php

declare(strict_types=1);

/*
 * TwilioMessagingSMSLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioMessagingSMSLib\Models\Builders;

use Core\Utils\CoreHelper;
use TwilioMessagingSMSLib\Models\Message;

/**
 * Builder for model Message
 *
 * @see Message
 */
class MessageBuilder
{
    /**
     * @var Message
     */
    private $instance;

    private function __construct(Message $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new message Builder object.
     */
    public static function init(
        string $accountSid,
        string $apiVersion,
        string $body,
        string $dateCreated,
        string $dateSent,
        string $dateUpdated,
        string $direction,
        int $errorCode,
        string $errorMessage,
        string $from,
        string $messagingServiceSid,
        string $numMedia,
        string $numSegments,
        string $price,
        string $priceUnit,
        string $sid,
        string $status,
        array $subresourceUris,
        string $to,
        string $uri
    ): self {
        return new self(new Message(
            $accountSid,
            $apiVersion,
            $body,
            $dateCreated,
            $dateSent,
            $dateUpdated,
            $direction,
            $errorCode,
            $errorMessage,
            $from,
            $messagingServiceSid,
            $numMedia,
            $numSegments,
            $price,
            $priceUnit,
            $sid,
            $status,
            $subresourceUris,
            $to,
            $uri
        ));
    }

    /**
     * Initializes a new message object.
     */
    public function build(): Message
    {
        return CoreHelper::clone($this->instance);
    }
}
