<?php

declare(strict_types=1);

/*
 * TwilioMessagingSMSLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioMessagingSMSLib\Models\Builders;

use Core\Utils\CoreHelper;
use TwilioMessagingSMSLib\Models\OK1;

/**
 * Builder for model OK1
 *
 * @see OK1
 */
class OK1Builder
{
    /**
     * @var OK1
     */
    private $instance;

    private function __construct(OK1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new ok1 Builder object.
     */
    public static function init(
        int $end,
        string $firstPageUri,
        array $messages,
        string $nextPageUri,
        int $page,
        int $pageSize,
        string $previousPageUri,
        int $start,
        string $uri
    ): self {
        return new self(
            new OK1($end, $firstPageUri, $messages, $nextPageUri, $page, $pageSize, $previousPageUri, $start, $uri)
        );
    }

    /**
     * Initializes a new ok1 object.
     */
    public function build(): OK1
    {
        return CoreHelper::clone($this->instance);
    }
}
