<?php

declare(strict_types=1);

/*
 * TwilioMessagingSMSLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioMessagingSMSLib\Models\Builders;

use Core\Utils\CoreHelper;
use TwilioMessagingSMSLib\Models\OK;

/**
 * Builder for model OK
 *
 * @see OK
 */
class OKBuilder
{
    /**
     * @var OK
     */
    private $instance;

    private function __construct(OK $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new ok Builder object.
     */
    public static function init(
        array $availablePhoneNumbers,
        int $end,
        string $firstPageUri,
        string $nextPageUri,
        int $page,
        int $pageSize,
        string $previousPageUri,
        int $start,
        string $uri
    ): self {
        return new self(new OK(
            $availablePhoneNumbers,
            $end,
            $firstPageUri,
            $nextPageUri,
            $page,
            $pageSize,
            $previousPageUri,
            $start,
            $uri
        ));
    }

    /**
     * Initializes a new ok object.
     */
    public function build(): OK
    {
        return CoreHelper::clone($this->instance);
    }
}
