<?php

declare(strict_types=1);

/*
 * TwilioMessagingSMSLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioMessagingSMSLib\Models;

use stdClass;

class Created implements \JsonSerializable
{
    /**
     * @var string
     */
    private $accountSid;

    /**
     * @var string
     */
    private $addressRequirements;

    /**
     * @var string
     */
    private $addressSid;

    /**
     * @var string
     */
    private $apiVersion;

    /**
     * @var bool
     */
    private $beta;

    /**
     * @var string
     */
    private $bundleSid;

    /**
     * @var array
     */
    private $capabilities;

    /**
     * @var string
     */
    private $dateCreated;

    /**
     * @var string
     */
    private $dateUpdated;

    /**
     * @var string
     */
    private $emergencyAddressSid;

    /**
     * @var string
     */
    private $emergencyStatus;

    /**
     * @var string
     */
    private $friendlyName;

    /**
     * @var string
     */
    private $identitySid;

    /**
     * @var string
     */
    private $origin;

    /**
     * @var string
     */
    private $phoneNumber;

    /**
     * @var string
     */
    private $sid;

    /**
     * @var string
     */
    private $smsApplicationSid;

    /**
     * @var string
     */
    private $smsFallbackMethod;

    /**
     * @var string
     */
    private $smsFallbackUrl;

    /**
     * @var string
     */
    private $smsMethod;

    /**
     * @var string
     */
    private $smsUrl;

    /**
     * @var string
     */
    private $status;

    /**
     * @var string
     */
    private $statusCallback;

    /**
     * @var string
     */
    private $statusCallbackMethod;

    /**
     * @var string
     */
    private $trunkSid;

    /**
     * @var string
     */
    private $uri;

    /**
     * @var string
     */
    private $voiceApplicationSid;

    /**
     * @var bool
     */
    private $voiceCallerIdLookup;

    /**
     * @var string
     */
    private $voiceFallbackMethod;

    /**
     * @var string
     */
    private $voiceFallbackUrl;

    /**
     * @var string
     */
    private $voiceMethod;

    /**
     * @var string
     */
    private $voiceReceiveMode;

    /**
     * @var string
     */
    private $voiceUrl;

    /**
     * @param string $accountSid
     * @param string $addressRequirements
     * @param string $addressSid
     * @param string $apiVersion
     * @param bool $beta
     * @param string $bundleSid
     * @param array $capabilities
     * @param string $dateCreated
     * @param string $dateUpdated
     * @param string $emergencyAddressSid
     * @param string $emergencyStatus
     * @param string $friendlyName
     * @param string $identitySid
     * @param string $origin
     * @param string $phoneNumber
     * @param string $sid
     * @param string $smsApplicationSid
     * @param string $smsFallbackMethod
     * @param string $smsFallbackUrl
     * @param string $smsMethod
     * @param string $smsUrl
     * @param string $status
     * @param string $statusCallback
     * @param string $statusCallbackMethod
     * @param string $trunkSid
     * @param string $uri
     * @param string $voiceApplicationSid
     * @param bool $voiceCallerIdLookup
     * @param string $voiceFallbackMethod
     * @param string $voiceFallbackUrl
     * @param string $voiceMethod
     * @param string $voiceReceiveMode
     * @param string $voiceUrl
     */
    public function __construct(
        string $accountSid,
        string $addressRequirements,
        string $addressSid,
        string $apiVersion,
        bool $beta,
        string $bundleSid,
        array $capabilities,
        string $dateCreated,
        string $dateUpdated,
        string $emergencyAddressSid,
        string $emergencyStatus,
        string $friendlyName,
        string $identitySid,
        string $origin,
        string $phoneNumber,
        string $sid,
        string $smsApplicationSid,
        string $smsFallbackMethod,
        string $smsFallbackUrl,
        string $smsMethod,
        string $smsUrl,
        string $status,
        string $statusCallback,
        string $statusCallbackMethod,
        string $trunkSid,
        string $uri,
        string $voiceApplicationSid,
        bool $voiceCallerIdLookup,
        string $voiceFallbackMethod,
        string $voiceFallbackUrl,
        string $voiceMethod,
        string $voiceReceiveMode,
        string $voiceUrl
    ) {
        $this->accountSid = $accountSid;
        $this->addressRequirements = $addressRequirements;
        $this->addressSid = $addressSid;
        $this->apiVersion = $apiVersion;
        $this->beta = $beta;
        $this->bundleSid = $bundleSid;
        $this->capabilities = $capabilities;
        $this->dateCreated = $dateCreated;
        $this->dateUpdated = $dateUpdated;
        $this->emergencyAddressSid = $emergencyAddressSid;
        $this->emergencyStatus = $emergencyStatus;
        $this->friendlyName = $friendlyName;
        $this->identitySid = $identitySid;
        $this->origin = $origin;
        $this->phoneNumber = $phoneNumber;
        $this->sid = $sid;
        $this->smsApplicationSid = $smsApplicationSid;
        $this->smsFallbackMethod = $smsFallbackMethod;
        $this->smsFallbackUrl = $smsFallbackUrl;
        $this->smsMethod = $smsMethod;
        $this->smsUrl = $smsUrl;
        $this->status = $status;
        $this->statusCallback = $statusCallback;
        $this->statusCallbackMethod = $statusCallbackMethod;
        $this->trunkSid = $trunkSid;
        $this->uri = $uri;
        $this->voiceApplicationSid = $voiceApplicationSid;
        $this->voiceCallerIdLookup = $voiceCallerIdLookup;
        $this->voiceFallbackMethod = $voiceFallbackMethod;
        $this->voiceFallbackUrl = $voiceFallbackUrl;
        $this->voiceMethod = $voiceMethod;
        $this->voiceReceiveMode = $voiceReceiveMode;
        $this->voiceUrl = $voiceUrl;
    }

    /**
     * Returns Account Sid.
     */
    public function getAccountSid(): string
    {
        return $this->accountSid;
    }

    /**
     * Sets Account Sid.
     *
     * @required
     * @maps account_sid
     */
    public function setAccountSid(string $accountSid): void
    {
        $this->accountSid = $accountSid;
    }

    /**
     * Returns Address Requirements.
     */
    public function getAddressRequirements(): string
    {
        return $this->addressRequirements;
    }

    /**
     * Sets Address Requirements.
     *
     * @required
     * @maps address_requirements
     */
    public function setAddressRequirements(string $addressRequirements): void
    {
        $this->addressRequirements = $addressRequirements;
    }

    /**
     * Returns Address Sid.
     */
    public function getAddressSid(): string
    {
        return $this->addressSid;
    }

    /**
     * Sets Address Sid.
     *
     * @required
     * @maps address_sid
     */
    public function setAddressSid(string $addressSid): void
    {
        $this->addressSid = $addressSid;
    }

    /**
     * Returns Api Version.
     */
    public function getApiVersion(): string
    {
        return $this->apiVersion;
    }

    /**
     * Sets Api Version.
     *
     * @required
     * @maps api_version
     */
    public function setApiVersion(string $apiVersion): void
    {
        $this->apiVersion = $apiVersion;
    }

    /**
     * Returns Beta.
     */
    public function getBeta(): bool
    {
        return $this->beta;
    }

    /**
     * Sets Beta.
     *
     * @required
     * @maps beta
     */
    public function setBeta(bool $beta): void
    {
        $this->beta = $beta;
    }

    /**
     * Returns Bundle Sid.
     */
    public function getBundleSid(): string
    {
        return $this->bundleSid;
    }

    /**
     * Sets Bundle Sid.
     *
     * @required
     * @maps bundle_sid
     */
    public function setBundleSid(string $bundleSid): void
    {
        $this->bundleSid = $bundleSid;
    }

    /**
     * Returns Capabilities.
     */
    public function getCapabilities(): array
    {
        return $this->capabilities;
    }

    /**
     * Sets Capabilities.
     *
     * @required
     * @maps capabilities
     */
    public function setCapabilities(array $capabilities): void
    {
        $this->capabilities = $capabilities;
    }

    /**
     * Returns Date Created.
     */
    public function getDateCreated(): string
    {
        return $this->dateCreated;
    }

    /**
     * Sets Date Created.
     *
     * @required
     * @maps date_created
     */
    public function setDateCreated(string $dateCreated): void
    {
        $this->dateCreated = $dateCreated;
    }

    /**
     * Returns Date Updated.
     */
    public function getDateUpdated(): string
    {
        return $this->dateUpdated;
    }

    /**
     * Sets Date Updated.
     *
     * @required
     * @maps date_updated
     */
    public function setDateUpdated(string $dateUpdated): void
    {
        $this->dateUpdated = $dateUpdated;
    }

    /**
     * Returns Emergency Address Sid.
     */
    public function getEmergencyAddressSid(): string
    {
        return $this->emergencyAddressSid;
    }

    /**
     * Sets Emergency Address Sid.
     *
     * @required
     * @maps emergency_address_sid
     */
    public function setEmergencyAddressSid(string $emergencyAddressSid): void
    {
        $this->emergencyAddressSid = $emergencyAddressSid;
    }

    /**
     * Returns Emergency Status.
     */
    public function getEmergencyStatus(): string
    {
        return $this->emergencyStatus;
    }

    /**
     * Sets Emergency Status.
     *
     * @required
     * @maps emergency_status
     */
    public function setEmergencyStatus(string $emergencyStatus): void
    {
        $this->emergencyStatus = $emergencyStatus;
    }

    /**
     * Returns Friendly Name.
     */
    public function getFriendlyName(): string
    {
        return $this->friendlyName;
    }

    /**
     * Sets Friendly Name.
     *
     * @required
     * @maps friendly_name
     */
    public function setFriendlyName(string $friendlyName): void
    {
        $this->friendlyName = $friendlyName;
    }

    /**
     * Returns Identity Sid.
     */
    public function getIdentitySid(): string
    {
        return $this->identitySid;
    }

    /**
     * Sets Identity Sid.
     *
     * @required
     * @maps identity_sid
     */
    public function setIdentitySid(string $identitySid): void
    {
        $this->identitySid = $identitySid;
    }

    /**
     * Returns Origin.
     */
    public function getOrigin(): string
    {
        return $this->origin;
    }

    /**
     * Sets Origin.
     *
     * @required
     * @maps origin
     */
    public function setOrigin(string $origin): void
    {
        $this->origin = $origin;
    }

    /**
     * Returns Phone Number.
     */
    public function getPhoneNumber(): string
    {
        return $this->phoneNumber;
    }

    /**
     * Sets Phone Number.
     *
     * @required
     * @maps phone_number
     */
    public function setPhoneNumber(string $phoneNumber): void
    {
        $this->phoneNumber = $phoneNumber;
    }

    /**
     * Returns Sid.
     */
    public function getSid(): string
    {
        return $this->sid;
    }

    /**
     * Sets Sid.
     *
     * @required
     * @maps sid
     */
    public function setSid(string $sid): void
    {
        $this->sid = $sid;
    }

    /**
     * Returns Sms Application Sid.
     */
    public function getSmsApplicationSid(): string
    {
        return $this->smsApplicationSid;
    }

    /**
     * Sets Sms Application Sid.
     *
     * @required
     * @maps sms_application_sid
     */
    public function setSmsApplicationSid(string $smsApplicationSid): void
    {
        $this->smsApplicationSid = $smsApplicationSid;
    }

    /**
     * Returns Sms Fallback Method.
     */
    public function getSmsFallbackMethod(): string
    {
        return $this->smsFallbackMethod;
    }

    /**
     * Sets Sms Fallback Method.
     *
     * @required
     * @maps sms_fallback_method
     */
    public function setSmsFallbackMethod(string $smsFallbackMethod): void
    {
        $this->smsFallbackMethod = $smsFallbackMethod;
    }

    /**
     * Returns Sms Fallback Url.
     */
    public function getSmsFallbackUrl(): string
    {
        return $this->smsFallbackUrl;
    }

    /**
     * Sets Sms Fallback Url.
     *
     * @required
     * @maps sms_fallback_url
     */
    public function setSmsFallbackUrl(string $smsFallbackUrl): void
    {
        $this->smsFallbackUrl = $smsFallbackUrl;
    }

    /**
     * Returns Sms Method.
     */
    public function getSmsMethod(): string
    {
        return $this->smsMethod;
    }

    /**
     * Sets Sms Method.
     *
     * @required
     * @maps sms_method
     */
    public function setSmsMethod(string $smsMethod): void
    {
        $this->smsMethod = $smsMethod;
    }

    /**
     * Returns Sms Url.
     */
    public function getSmsUrl(): string
    {
        return $this->smsUrl;
    }

    /**
     * Sets Sms Url.
     *
     * @required
     * @maps sms_url
     */
    public function setSmsUrl(string $smsUrl): void
    {
        $this->smsUrl = $smsUrl;
    }

    /**
     * Returns Status.
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @required
     * @maps status
     */
    public function setStatus(string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Status Callback.
     */
    public function getStatusCallback(): string
    {
        return $this->statusCallback;
    }

    /**
     * Sets Status Callback.
     *
     * @required
     * @maps status_callback
     */
    public function setStatusCallback(string $statusCallback): void
    {
        $this->statusCallback = $statusCallback;
    }

    /**
     * Returns Status Callback Method.
     */
    public function getStatusCallbackMethod(): string
    {
        return $this->statusCallbackMethod;
    }

    /**
     * Sets Status Callback Method.
     *
     * @required
     * @maps status_callback_method
     */
    public function setStatusCallbackMethod(string $statusCallbackMethod): void
    {
        $this->statusCallbackMethod = $statusCallbackMethod;
    }

    /**
     * Returns Trunk Sid.
     */
    public function getTrunkSid(): string
    {
        return $this->trunkSid;
    }

    /**
     * Sets Trunk Sid.
     *
     * @required
     * @maps trunk_sid
     */
    public function setTrunkSid(string $trunkSid): void
    {
        $this->trunkSid = $trunkSid;
    }

    /**
     * Returns Uri.
     */
    public function getUri(): string
    {
        return $this->uri;
    }

    /**
     * Sets Uri.
     *
     * @required
     * @maps uri
     */
    public function setUri(string $uri): void
    {
        $this->uri = $uri;
    }

    /**
     * Returns Voice Application Sid.
     */
    public function getVoiceApplicationSid(): string
    {
        return $this->voiceApplicationSid;
    }

    /**
     * Sets Voice Application Sid.
     *
     * @required
     * @maps voice_application_sid
     */
    public function setVoiceApplicationSid(string $voiceApplicationSid): void
    {
        $this->voiceApplicationSid = $voiceApplicationSid;
    }

    /**
     * Returns Voice Caller Id Lookup.
     */
    public function getVoiceCallerIdLookup(): bool
    {
        return $this->voiceCallerIdLookup;
    }

    /**
     * Sets Voice Caller Id Lookup.
     *
     * @required
     * @maps voice_caller_id_lookup
     */
    public function setVoiceCallerIdLookup(bool $voiceCallerIdLookup): void
    {
        $this->voiceCallerIdLookup = $voiceCallerIdLookup;
    }

    /**
     * Returns Voice Fallback Method.
     */
    public function getVoiceFallbackMethod(): string
    {
        return $this->voiceFallbackMethod;
    }

    /**
     * Sets Voice Fallback Method.
     *
     * @required
     * @maps voice_fallback_method
     */
    public function setVoiceFallbackMethod(string $voiceFallbackMethod): void
    {
        $this->voiceFallbackMethod = $voiceFallbackMethod;
    }

    /**
     * Returns Voice Fallback Url.
     */
    public function getVoiceFallbackUrl(): string
    {
        return $this->voiceFallbackUrl;
    }

    /**
     * Sets Voice Fallback Url.
     *
     * @required
     * @maps voice_fallback_url
     */
    public function setVoiceFallbackUrl(string $voiceFallbackUrl): void
    {
        $this->voiceFallbackUrl = $voiceFallbackUrl;
    }

    /**
     * Returns Voice Method.
     */
    public function getVoiceMethod(): string
    {
        return $this->voiceMethod;
    }

    /**
     * Sets Voice Method.
     *
     * @required
     * @maps voice_method
     */
    public function setVoiceMethod(string $voiceMethod): void
    {
        $this->voiceMethod = $voiceMethod;
    }

    /**
     * Returns Voice Receive Mode.
     */
    public function getVoiceReceiveMode(): string
    {
        return $this->voiceReceiveMode;
    }

    /**
     * Sets Voice Receive Mode.
     *
     * @required
     * @maps voice_receive_mode
     */
    public function setVoiceReceiveMode(string $voiceReceiveMode): void
    {
        $this->voiceReceiveMode = $voiceReceiveMode;
    }

    /**
     * Returns Voice Url.
     */
    public function getVoiceUrl(): string
    {
        return $this->voiceUrl;
    }

    /**
     * Sets Voice Url.
     *
     * @required
     * @maps voice_url
     */
    public function setVoiceUrl(string $voiceUrl): void
    {
        $this->voiceUrl = $voiceUrl;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['account_sid']            = $this->accountSid;
        $json['address_requirements']   = $this->addressRequirements;
        $json['address_sid']            = $this->addressSid;
        $json['api_version']            = $this->apiVersion;
        $json['beta']                   = $this->beta;
        $json['bundle_sid']             = $this->bundleSid;
        $json['capabilities']           = $this->capabilities;
        $json['date_created']           = $this->dateCreated;
        $json['date_updated']           = $this->dateUpdated;
        $json['emergency_address_sid']  = $this->emergencyAddressSid;
        $json['emergency_status']       = $this->emergencyStatus;
        $json['friendly_name']          = $this->friendlyName;
        $json['identity_sid']           = $this->identitySid;
        $json['origin']                 = $this->origin;
        $json['phone_number']           = $this->phoneNumber;
        $json['sid']                    = $this->sid;
        $json['sms_application_sid']    = $this->smsApplicationSid;
        $json['sms_fallback_method']    = $this->smsFallbackMethod;
        $json['sms_fallback_url']       = $this->smsFallbackUrl;
        $json['sms_method']             = $this->smsMethod;
        $json['sms_url']                = $this->smsUrl;
        $json['status']                 = $this->status;
        $json['status_callback']        = $this->statusCallback;
        $json['status_callback_method'] = $this->statusCallbackMethod;
        $json['trunk_sid']              = $this->trunkSid;
        $json['uri']                    = $this->uri;
        $json['voice_application_sid']  = $this->voiceApplicationSid;
        $json['voice_caller_id_lookup'] = $this->voiceCallerIdLookup;
        $json['voice_fallback_method']  = $this->voiceFallbackMethod;
        $json['voice_fallback_url']     = $this->voiceFallbackUrl;
        $json['voice_method']           = $this->voiceMethod;
        $json['voice_receive_mode']     = $this->voiceReceiveMode;
        $json['voice_url']              = $this->voiceUrl;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
