<?php

declare(strict_types=1);

/*
 * TwilioMessagingSMSLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioMessagingSMSLib;

use CoreInterfaces\Http\HttpConfigurations;

/**
 * An interface for all configuration parameters required by the SDK.
 */
interface ConfigurationInterface extends HttpConfigurations
{
    /**
     * Get current API environment
     */
    public function getEnvironment(): string;

    /**
     * Get (Required) The SID of the [Account](https://www.twilio.com/docs/iam/api/account) requesting the
     *
     * * AvailablePhoneNumber resources.
     */
    public function getAccountSid(): string;

    /**
     * Get the credentials to use with BasicAuth
     */
    public function getBasicAuthCredentials(): ?BasicAuthCredentials;

    /**
     * Get the base uri for a given server in the current environment.
     *
     * @param string $server Server name
     *
     * @return string Base URI
     */
    public function getBaseUri(string $server = Server::SERVER_1): string;
}
